openapi: 3.0.3
info:
  title: Mastercard Developer Hub for FDX APIs FDX Authorization Server Application Check Controller API
  version: 1.0.0
  description: Dynamic Client Registration, Token, Introspection, Authorize API
  contact:
    name: API Support
    email: apisupport@mastercard.com
    url: https://developer.mastercard.com/support
servers:
- url: http://localhost:8080
  description: Localhost URL
tags:
- name: Application Check Controller
  description: health check and check the status application
paths:
  /startupStatus:
    get:
      tags:
      - Application Check Controller
      summary: Mastercard Developer Hub for FDX APIs Status check
      description: status check for application
      operationId: getStartupStatus
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /shutdown:
    get:
      tags:
      - Application Check Controller
      summary: Mastercard Developer Hub for FDX APIs shutdown application
      description: Return the status of shutdown.
      operationId: shutdown
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /livenessProbe:
    get:
      tags:
      - Application Check Controller
      summary: Mastercard Developer Hub for FDX APIs liveness check
      description: liveness check for application
      operationId: validateLiveness
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /health:
    get:
      tags:
      - Application Check Controller
      summary: Mastercard Developer Hub for FDX APIs health check
      description: health check for application
      operationId: getHealth
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
